### ISSUE TITLE
adding Cragg-Donald (1993) weak instrument test

### ISSUE THREAD

**Issue by jkurle** [john-d-fox/ivreg#5]
Hi everyone,

First of all thank you for creating this great package, which I have used heavily for a while now.

I thought it would be a useful addition to the package to provide a function that calculates the Cragg-Donald (1993) test statistic. This would be more informative than the usual first stage F-tests when the model has several endogenous variables. I have already coded my own version of the CD statistic for specific applications and could either write a method or a function (potentially to be incorporated into `ivdiag()`) that calculates the test statistic.

Following the open source netiquette, I wanted to first ask whether such a contribution would be welcomed and if yes, whether you have any suggestions about how best to add this functionality (e.g. separate method/function etc.).

**Comment by zeileis** [comment]
Thanks for the suggestion. I'm not familiar with the Cragg-Donald test - because I'm really not very familiar with instrumental variables regression and just mostly use it for teaching. Hence I wanted to have a look what would be needed to implement the test. This showed that there are various follow-up works like those from Stock & Yogo or more recently by Sanderson & Windmeijer which suggests that it is not so clear cut which version of test should be used. Moreover, [this discussion on StackExchange](https://stats.stackexchange.com/questions/107922/interpreting-significance-of-cragg-donald-f-statistic-for-weak-instruments#107931) links a number of other references and points out that in Stata there are dedicated extension packages for these tests.

Therefore, I'm not sure what would be most appropriate here. Just adding one particular version of these tests might not be the best solution. Possibly extension packages as in Stata might be better?

**Comment by jkurle** [comment]
Thank you for your quick reply. I'm familiar with Stock & Yogo, which provide a set of critical values to bound the bias from weak instruments. This means that the Cragg-Donald test would still be calculated as usual but the researcher would have to choose the critical value depending on their preferences. So this probably belongs in the "art of modelling" section and an R package cannot take that responsibility from the researcher. I'm not familiar with the Sanderson & Windmeijer paper yet but will have a look.

I might then implement several weak instrument tests in a separate package as per your suggestion.

**Comment by zeileis** [comment]
Thanks! Let us know if you have written such a package. In the meantime I will close this issue for now.
Another comment: I was just pointed to this recent papers of Skeels & Windmeijer which provides closed-form solutions related to the Stock & Yogo tables, [doi:10.3390/econometrics6040044](https://doi.org/10.3390/econometrics6040044).

**Comment by zeileis** [comment]
Just realized that I can't close this myself. @john-d-fox could you do so?

**Comment by jkurle** [comment]
Thanks for the reference, this will indeed be very useful for the implementation of critical values in a package. I think I can close the issue, being the one who opened it.

**Comment by john-d-fox** [comment]
Hi,

My preferred approach would be to provide these kinds of tests as 
separate functions in the ivreg package. Recall (Achim) that I initially 
suggested we do that for the tests currently in the summary() output for 
ivreg objects. After some discussion, we decided not to do that for 
backwards compatibility with ivreg() output from the AER package.

Best,
  John
